In [3]:
import numpy as np

In [9]:
ornek = np.random.randint(50,300, size=(7,5))

In [12]:
ornek

array([[ 95, 199, 240,  77,  91],
       [220, 156,  86, 272,  72],
       [ 54,  68, 296, 130, 288],
       [250,  72, 221, 156,  70],
       [218,  89, 148, 146, 187],
       [123,  66, 105, 257, 207],
       [256, 194, 187, 135,  50]], dtype=int32)

In [20]:
ornek.shape
# kaç satır kaç sütün

(7, 5)

In [21]:
ornek.ndim
## dizinin kaç boyutlu olduğunu söyler

2

In [22]:
ornek.dtype
# veri tipi nedir?

dtype('int32')

In [23]:
ornek.size
# toplam eleman sayısı

35

In [27]:
ornek[2]
# belirli bir günün satışları

array([ 54,  68, 296, 130, 288], dtype=int32)

In [30]:
ornek[:, 4]
# belirli bir ürünün haftalık satışı

array([ 91,  72, 288,  70, 187, 207,  50], dtype=int32)

In [34]:
ornek[:3]
#ilk 3 gün

array([[ 95, 199, 240,  77,  91],
       [220, 156,  86, 272,  72],
       [ 54,  68, 296, 130, 288]], dtype=int32)

In [60]:
toplam = ornek.sum()

In [36]:
ornek.mean()

np.float64(156.6)

In [37]:
ornek.max()

np.int32(296)

In [38]:
ornek.min()

np.int32(50)

In [70]:
ayniUrunToplami = ornek.sum(axis = 0)

In [71]:
ayniUrunToplami

array([1216,  844, 1283, 1173,  965])

In [72]:
gunlerToplami = ornek.sum(axis = 1)

In [73]:
gunlerToplami

array([702, 806, 836, 769, 788, 758, 822])

In [74]:
# axis = 0 aşağı doğru, axis = 1 yana doğru çalışır

In [75]:
yeniOrnek = ornek.reshape(35,1)

In [76]:
yeniOrnek

array([[ 95],
       [199],
       [240],
       [ 77],
       [ 91],
       [220],
       [156],
       [ 86],
       [272],
       [ 72],
       [ 54],
       [ 68],
       [296],
       [130],
       [288],
       [250],
       [ 72],
       [221],
       [156],
       [ 70],
       [218],
       [ 89],
       [148],
       [146],
       [187],
       [123],
       [ 66],
       [105],
       [257],
       [207],
       [256],
       [194],
       [187],
       [135],
       [ 50]], dtype=int32)

In [77]:
ornek.transpose()

array([[ 95, 220,  54, 250, 218, 123, 256],
       [199, 156,  68,  72,  89,  66, 194],
       [240,  86, 296, 221, 148, 105, 187],
       [ 77, 272, 130, 156, 146, 257, 135],
       [ 91,  72, 288,  70, 187, 207,  50]], dtype=int32)

In [78]:
ornek.flatten()

array([ 95, 199, 240,  77,  91, 220, 156,  86, 272,  72,  54,  68, 296,
       130, 288, 250,  72, 221, 156,  70, 218,  89, 148, 146, 187, 123,
        66, 105, 257, 207, 256, 194, 187, 135,  50], dtype=int32)

In [79]:
ornek.ravel()

array([ 95, 199, 240,  77,  91, 220, 156,  86, 272,  72,  54,  68, 296,
       130, 288, 250,  72, 221, 156,  70, 218,  89, 148, 146, 187, 123,
        66, 105, 257, 207, 256, 194, 187, 135,  50], dtype=int32)

In [84]:
print(f"Toplam haftalık satış: {toplam}")
a = ayniUrunToplami.argmax()
print(f"En çok satan ürün: {a}.sütun")
b = gunlerToplami.argmax()
print(f"En çok satan gün: {b}.gün")

Toplam haftalık satış: 5481
En çok satan ürün: 2.sütun
En çok satan gün: 2.gün
