Bir şirketin **8 çalışana ait 6 aylık performans skorları** NumPy ile analiz edilecektir.

- Satırlar → Çalışanlar
- Sütunlar → Aylar
- Değerler → Performans puanı (0–100)

In [6]:
import numpy as np

In [14]:
performans = np.random.randint(50,100, size=(8,6))

In [15]:
performans

array([[75, 80, 77, 83, 81, 74],
       [95, 74, 72, 61, 92, 53],
       [53, 74, 50, 74, 61, 97],
       [84, 74, 96, 53, 73, 85],
       [83, 78, 56, 82, 59, 80],
       [79, 69, 78, 51, 82, 88],
       [58, 52, 59, 68, 57, 73],
       [84, 88, 90, 78, 95, 70]], dtype=int32)

In [25]:
performans.shape

(8, 6)

In [26]:
performans.ndim

2

In [27]:
performans.dtype

dtype('int32')

In [28]:
performans.size

48

In [30]:
# ilk çalışanın tüm ayları
performans[0,:]

array([75, 80, 77, 83, 81, 74], dtype=int32)

In [31]:
# son ayın tüm çalışanları
performans[:,5]

array([74, 53, 97, 85, 80, 88, 73, 70], dtype=int32)

In [32]:
# ilk 3 çalışanın ilk 2 ayını seç
performans[:3,:2]

array([[75, 80],
       [95, 74],
       [53, 74]], dtype=int32)

In [33]:
# belirli bir çalışanın belirli ay skorunu al
performans[4,2]

np.int32(56)

In [39]:
# sub-matrix
subMatrix = performans[2:5,1:5]

In [40]:
subMatrix

array([[74, 50, 74, 61],
       [74, 96, 53, 73],
       [78, 56, 82, 59]], dtype=int32)

In [41]:
yeniPerformans = performans + 5

In [42]:
yeniPerformans

array([[ 80,  85,  82,  88,  86,  79],
       [100,  79,  77,  66,  97,  58],
       [ 58,  79,  55,  79,  66, 102],
       [ 89,  79, 101,  58,  78,  90],
       [ 88,  83,  61,  87,  64,  85],
       [ 84,  74,  83,  56,  87,  93],
       [ 63,  57,  64,  73,  62,  78],
       [ 89,  93,  95,  83, 100,  75]], dtype=int32)

In [44]:
normalize = (performans / performans.max()) * 100

In [45]:
normalize

array([[ 77.31958763,  82.4742268 ,  79.3814433 ,  85.56701031,
         83.50515464,  76.28865979],
       [ 97.93814433,  76.28865979,  74.22680412,  62.88659794,
         94.84536082,  54.63917526],
       [ 54.63917526,  76.28865979,  51.54639175,  76.28865979,
         62.88659794, 100.        ],
       [ 86.59793814,  76.28865979,  98.96907216,  54.63917526,
         75.25773196,  87.62886598],
       [ 85.56701031,  80.41237113,  57.73195876,  84.53608247,
         60.82474227,  82.4742268 ],
       [ 81.44329897,  71.13402062,  80.41237113,  52.57731959,
         84.53608247,  90.72164948],
       [ 59.79381443,  53.60824742,  60.82474227,  70.10309278,
         58.7628866 ,  75.25773196],
       [ 86.59793814,  90.72164948,  92.78350515,  80.41237113,
         97.93814433,  72.16494845]])

In [46]:
ay1 = performans[:,0]
ay2 = performans[:,1]

In [48]:
print(ay1 > ay2)

[False  True False  True  True  True  True False]


In [49]:
calisanBazli = performans.mean(axis=1)

In [63]:
calisanBazli

array([78.33333333, 74.5       , 68.16666667, 77.5       , 73.        ,
       74.5       , 61.16666667, 84.16666667])

In [51]:
ayBazli = performans.mean(axis=0)

In [64]:
ayBazli

array([76.375, 73.625, 72.25 , 68.75 , 75.   , 77.5  ])

In [ ]:
# axis = 0 aşağı doğru, axis = 1 yana doğru çalışır

In [54]:
yuksekPerformans = performans.argmax()
dusukPerformans = performans.argmin()

In [55]:
dusukPerformans

np.int64(14)

In [56]:
performans.reshape(12,4)

array([[75, 80, 77, 83],
       [81, 74, 95, 74],
       [72, 61, 92, 53],
       [53, 74, 50, 74],
       [61, 97, 84, 74],
       [96, 53, 73, 85],
       [83, 78, 56, 82],
       [59, 80, 79, 69],
       [78, 51, 82, 88],
       [58, 52, 59, 68],
       [57, 73, 84, 88],
       [90, 78, 95, 70]], dtype=int32)

In [58]:
performans.transpose()

array([[75, 95, 53, 84, 83, 79, 58, 84],
       [80, 74, 74, 74, 78, 69, 52, 88],
       [77, 72, 50, 96, 56, 78, 59, 90],
       [83, 61, 74, 53, 82, 51, 68, 78],
       [81, 92, 61, 73, 59, 82, 57, 95],
       [74, 53, 97, 85, 80, 88, 73, 70]], dtype=int32)

In [60]:
performans.flatten()

array([75, 80, 77, 83, 81, 74, 95, 74, 72, 61, 92, 53, 53, 74, 50, 74, 61,
       97, 84, 74, 96, 53, 73, 85, 83, 78, 56, 82, 59, 80, 79, 69, 78, 51,
       82, 88, 58, 52, 59, 68, 57, 73, 84, 88, 90, 78, 95, 70],
      dtype=int32)

In [61]:
performans.ravel()

array([75, 80, 77, 83, 81, 74, 95, 74, 72, 61, 92, 53, 53, 74, 50, 74, 61,
       97, 84, 74, 96, 53, 73, 85, 83, 78, 56, 82, 59, 80, 79, 69, 78, 51,
       82, 88, 58, 52, 59, 68, 57, 73, 84, 88, 90, 78, 95, 70],
      dtype=int32)

In [68]:
print(f"En başarılı çalışan: {performans.argmax()}")
print(f"En tembel çalışan: {performans.argmin()}")
print(f"En yüksek ay ortalaması: {ayBazli.max()}")
print(f"En yüksek çalışan ortalaması: {calisanBazli.max()}")
print(f"Genel ortalama performans: {performans.mean()}")

En başarılı çalışan: 17
En tembel çalışan: 14
En yüksek ay ortalaması: 77.5
En yüksek çalışan ortalaması: 84.16666666666667
Genel ortalama performans: 73.91666666666667
